/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z0Oin6iVjVK
 */

"use client";

import { useState, useEffect } from "react";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  CardContent,
  Card,
  CardTitle,
  CardDescription,
  CardHeader,
} from "@/components/ui/card";
import Link from "next/link";
import useDataSearch from "@/hooks/useDataSearch";

export function Component() {
  const [outages, setOutages] = useState({
    data: {
      address: "",
      message: "",
      isOutage: false,
    },
    // loading: false,
  });
  const [loading, setLoading] = useState(false);
  const { searchResult, searchData } = useDataSearch();
  const handleCheckAddressClick = () => {
    setOutages({
      data: {
        address: "",
        message: "",
        isOutage: false,
      },
      // loading: true,
    });
    setLoading(true);
    // Simulate loading
    setTimeout(() => {
      setOutages({
        data: {
          address: "Ахсарова 19",
          message: "Відключення електроенергії з 10:00 до 14:00",
          isOutage: true,
        },
        // loading: false,
      });
      setLoading(false);
    }, 2000);

    // console.log(searchData("вул. Ахсарова", "19"));
    searchData("Ахсарова", "19");
  };
  console.log(searchResult);

  // console.log();

  // useEffect(() => {
  //   console.log(searchData("Ахсарова", "19"));
  // }, [outages.data.address, loading]);

  // useEffect(() => {
  //   // Fetch outages data
  //   // fetch("https://api.example.com/outages")
  //   //   .then((response) => response.json())
  //   //   .then((data) => setOutages(data));

  //   // Simulate loading
  //   // setTimeout(() => {
  //   //   setOutages({
  //   //     data: {
  //   //       address: "Ахсарова 19",
  //   //       message: "Відключення електроенергії з 10:00 до 14:00",
  //   //     },
  //   //     loading: false,
  //   //   });
  //   // }, 2000);

  //   // Cleanup
  //   return () => {
  //     setOutages({
  //       data: {
  //         address: "Ахсарова 19",
  //         message: "Відключення електроенергії з 10:00 до 14:00",
  //         isOutage: true,
  //       },
  //       loading: false,
  //     });
  //   };
  // }, []);
  return (
    <>
      <div className="px-4 py-6 md:py-12 lg:py-16">
        <div className="container grid items-start gap-4 md:gap-8">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Перевірте наявність відключень
            </h1>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Введіть свою адресу, щоб побачити, чи є повідомлення про
              відключення за вашою адресою.
            </p>
          </div>
          <div className="container flex flex-col lg:flex-row items-start gap-4 md:gap-8">
            <Card className="w-full max-w-[400px] divide-y">
              <CardContent className="p-4 md:p-6 space-y-4">
                <div className="space-y-2">
                  <Label className="text-sm font-medium" htmlFor="address">
                    Введіть свою адресу
                  </Label>
                  <Input id="address" placeholder="Ахсарова 19" type="text" />
                </div>
                <Button size="lg" onClick={handleCheckAddressClick}>
                  Перевірте наявність відключень
                </Button>
              </CardContent>
              <CardContent className="p-4 md:p-6 flex items-center justify-between">
                {/* <div className="flex items-center gap-2">
                  <ShieldCheckIcon className="w-5 h-5" />У вашому регіоні немає
                  повідомлень про відключення електроенергії
                </div> */}
                <Button size="sm" /*variant="text"*/>
                  Зберегти адресу
                </Button>
              </CardContent>
            </Card>
            {
              // Add a card with the following content if there are any outages
              // outages.data.isOutage ? (
              searchResult.map((element: any, index: number) => (
                // !loading ? (
                <Card key={index} className="w-full max-w-[400px] divide-y">
                  <CardContent className="p-4 md:p-6 space-y-4">
                    <div className="space-y-2">
                      <h3 className="text-lg font-semibold">
                        {element.street}
                      </h3>
                      <p className="text-sm text-gray-500">
                        {outages.data.message}
                      </p>
                    </div>
                  </CardContent>
                </Card>
                // ) : (
                // Spinner()
                // )
              ))
              // ) : (
              //   <div className="w-full max-w-[400px]">
              //     <Card className="w-full max-w-[400px] divide-y">
              //       <CardContent className="p-4 md:p-6 space-y-4">
              //         <div className="space-y-2">
              //           <h3 className="text-lg font-semibold">
              //             Немає відключень
              //           </h3>
              //           <p className="text-sm text-gray-500">
              //             У вашому регіоні немає повідомлень про відключення
              //             електроенергії
              //           </p>
              //         </div>
              //       </CardContent>
              //     </Card>
              //   </div>
              // )
            }
          </div>
        </div>
      </div>
      <section className="border-t py-8 md:py-16">
        <div className="container grid items-start gap-4 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Що робити під час відключення електроенергії
            </h2>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Підготуйтеся до наступного відключення електроенергії,
              скориставшись цими порадами.
            </p>
          </div>
          <div className="grid gap-4 md:grid-cols-3 md:gap-8 lg:grid-cols-3 lg:gap-10">
            <Card className="flex flex-col gap-2">
              <Link className="inline-block" href="#">
                <img
                  alt="Image"
                  className="aspect-video overflow-hidden object-cover rounded-lg"
                  height={400}
                  src="/placeholder.svg"
                  width={600}
                />
                <CardHeader className="flex flex-col gap-1 p-4">
                  <CardTitle className="text-base font-semibold line-clamp-2">
                    Як підготуватися до відключення електроенергії
                  </CardTitle>
                  <CardDescription className="text-sm line-clamp-2">
                    Поради, як підготуватися до відключення електроенергії.
                  </CardDescription>
                </CardHeader>
              </Link>
            </Card>
            <Card className="flex flex-col gap-2">
              <Link className="inline-block" href="#">
                <img
                  alt="Image"
                  className="aspect-video overflow-hidden object-cover rounded-lg"
                  height={400}
                  src="/placeholder.svg"
                  width={600}
                />
                <CardHeader className="flex flex-col gap-1 p-4">
                  <CardTitle className="text-base font-semibold line-clamp-2">
                    Як підготуватися до відключення електроенергії
                  </CardTitle>
                  <CardDescription className="text-sm line-clamp-2">
                    Поради, як підготуватися до відключення електроенергії.
                  </CardDescription>
                </CardHeader>
              </Link>
            </Card>
            <Card className="flex flex-col gap-2">
              <Link className="inline-block" href="#">
                <img
                  alt="Image"
                  className="aspect-video overflow-hidden object-cover rounded-lg"
                  height={400}
                  src="/placeholder.svg"
                  width={600}
                />
                <CardHeader className="flex flex-col gap-1 p-4">
                  <CardTitle className="text-base font-semibold line-clamp-2">
                    Як підготуватися до відключення електроенергії
                  </CardTitle>
                  <CardDescription className="text-sm line-clamp-2">
                    Поради, як підготуватися до відключення електроенергії.
                  </CardDescription>
                </CardHeader>
              </Link>
            </Card>
          </div>
        </div>
      </section>
    </>
  );
}

function ShieldCheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}

// Loading spinner component
function Spinner(/*props*/) {
  return (
    <svg
      // {...props}
      className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle
        className="opacity-25"
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="4"
      ></circle>
      <path
        className="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A8.001 8.001 0 0112 4.472v3.09a4.001 4.001 0 00-4 4.729L6 12h4v5.291z"
      ></path>
    </svg>
  );
}
